LAB_NAME="v6bench"
LAB_DESCRIPTION="V6Bench IPv4/IPv6 connectivity benchmark"
LAB_VERSION="0.1"

# --------------------------------------------------
# Internal LAN
# --------------------------------------------------

gateway[0]="LAB"
nat64[0]="LAB"
siit[0]="LAB"
dns[0]="LAB"

dual_client[0]="LAB"
ipv4_client[0]="LAB"
ipv6_strict_client[0]="LAB"
ipv6_nat64_client[0]="LAB"

# --------------------------------------------------
# Images
# --------------------------------------------------

gateway[image]="kathara/base"
nat64[image]="kathara/base"
siit[image]="kathara/base"
dns[image]="kathara/bind"

dual_client[image]="kathara/base"
ipv4_client[image]="kathara/base"
ipv6_strict_client[image]="kathara/base"
ipv6_nat64_client[image]="kathara/base"

# --------------------------------------------------
# IPv6
# --------------------------------------------------

gateway[ipv6]="true"
nat64[ipv6]="true"
siit[ipv6]="true"
dns[ipv6]="true"

dual_client[ipv6]="true"
ipv4_client[ipv6]="false"
ipv6_strict_client[ipv6]="true"
ipv6_nat64_client[ipv6]="true"

# --------------------------------------------------
# IPs
# --------------------------------------------------

gateway[env]="IPv6_ADDR=2001:db8:1::1/64"
nat64[env]="IPv6_ADDR=2001:db8:1::64/64"
siit[env]="IPv6_ADDR=2001:db8:1::46/64"
dns[env]="IPv6_ADDR=2001:db8:1::53/64"
gateway[env]="IPv4_ADDR=192.168.0.1/24"
nat64[env]="IPv4_ADDR=192.168.0.64/24"
siit[env]="IPv4_ADDR=192.168.0.46/24"
dns[env]="IPv4_ADDR=192.168.0.53/24"

dual_client[env]="IPv6_ADDR=2001:db8:1::10/64"
dual_client[env]="IPv4_ADDR=192.168.0.10/24"
ipv4_client[env]="IPv4_ADDR=192.168.0.40/24"
ipv6_strict_client[env]="IPv6_ADDR=2001:db8:1::60/64"
ipv6_nat64_client[env]="IPv6_ADDR=2001:db8:1::664/64"

# --------------------------------------------------
# Device_specific Settings
# --------------------------------------------------

# gateway
gateway[bridged]="true"
gateway[env]="IS_GATEWAY=true"
gateway[entrypoint]="/bin/sh /shared/shared_data/srv_entrypoint.sh"

# dns
dns[entrypoint]="/bin/sh /shared/shared_data/srv_entrypoint.sh"

# nat64
nat64[privileged]="true"
nat64[volume]="/usr/src|/usr/src|rw"
nat64[volume]="/lib/modules|/lib/modules|rw"
nat64[entrypoint]="/bin/sh /shared/shared_data/srv_entrypoint.sh"

# siit
siit[privileged]="true"
siit[volume]="/usr/src|/usr/src|rw"
siit[volume]="/lib/modules|/lib/modules|rw"
siit[entrypoint]="/bin/sh /shared/shared_data/srv_entrypoint.sh"

# dual_client
dual_client[env]="SDOMS=dual ipv4 ipv6"
dual_client[entrypoint]="/bin/sh /shared/shared_data/test_runner.sh"

# ipv4_client
ipv4_client[env]="SDOMS=dual ipv4 siit"
ipv4_client[entrypoint]="/bin/sh /shared/shared_data/test_runner.sh"

# ipv6_strict_client
ipv6_strict_client[env]="SDOMS=dual ipv6"
ipv6_strict_client[entrypoint]="/bin/sh /shared/shared_data/test_runner.sh"

# ipv6_nat64_client
ipv6_nat64_client[env]="SDOMS=ipv4 ipv6"
ipv6_nat64_client[entrypoint]="/bin/sh /shared/shared_data/test_runner.sh"